# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Flickr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'Kingfisher', '~> 4.9'
  pod 'SwiftLint', '0.27.0'
  pod 'SwiftyJSON', '4.1.0'
end
